server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/securitydb
    username: security
    password: supersecretpassword
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

jwt:
  secret: MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCBh3+ToDdTAkVCP83FpmiHsIe0j6a6WRtYgHES9atxsCw==
  expiration: 900000
  refresh-expiration: 604800000

